src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/services/authentication.service.ts
Refresh page to correctly display saved profile counts when the user has saved a profile (Career or Industry) while offline.  
This is my first time creating a PR on this code base so review carefully.  Specifically, it appears as if the Angular code is built during deployment (as it should).
=> [WR-1386] refresh page to correctly display saved profile counts

src/WorkBC.ElasticSearch.Search/Queries/JobSearchQuery.cs, src/WorkBC.Tests/Tests/JobSearchQueryTest.cs
Modify API so custom job board queries that filter based on PostedDate include the ending date too.  Refactor to make code more testable.
=> [WBCAMS-113] date range queries include end date

src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/filters/models/base-component.model.ts, src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/filters/services/filter.service.ts, src/WorkBC.Web/ClientApp/projects/jb-search/src/app/job-search/results/results.component.ts
At present, when **mobile** users enter filter criteria and click search, the application automatically scrolls the user to the results section of the page.  This PR removes this functionality.
=> [WR-1436] remove mobile auto-scroll

src/WorkBC.Shared/Services/GeocodingCachingService.cs, src/WorkBC.Shared/Services/GeocodingService.cs, src/WorkBC.Shared/Services/IGeocodingService.cs, src/WorkBC.Tests/FakeServices/FakeGeocodingService.cs, src/WorkBC.Tests/Tests/GeocodingServiceTests.cs, src/WorkBC.Web/Startup.cs
This pull request should fix the issue that caused the build failure on Thursday / Friday.  I had inadvertently created a circular dependency.  Now, we're using two interfaces -- one for the API (base) class and another for the caching layer that extends the base.  I'm using separate classes to make them testable.
=> [WBCAMS-200] add interface for geocoding api class

src/WorkBC.Web/Helpers/BadHttpRequestExceptionFilter.cs, src/WorkBC.Web/Startup.cs
Add a filter to gracefully handle a `BadHttpRequestException`
Using curl, we can trigger the exception like by telling the server expect a payload that's longer than what we actually send.  Like this:
`curl -X 'POST' 'http://192.168.10.197:9223/api/Search/JobSearch' -H 'Content-Type: application/json' -H 'Content-Length: 200' -d '{"Page":1"'`
Prior to this pull request, the server responds with an exception, like this:
> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
>    at …
=> [WBCAMS-220] gracefully handle BadHttpRequestException

src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/item/item.component.ts, src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/filters/models/job.model.ts
Second attempt to fix this issue.  This pull request now uses the same logic when calculating `IsExpired()` and `ExpiresIn()`.  There's a small number of lines now duplicated, but without unit tests, I'm hesitant to clean it up.
=> [WBCAMS-264] do not grey out expired jobs rev2

src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/pagination/pagination.component.ts, src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/search-criteries/search-criteries.component.ts
Fix two pagination issues:
- when returning from job detail page, display the correct page in the footer
- when filters are cleared, return to page 1
=> [WBCAMS-279] and [WBCAMS-278] fix pagination issues

src/WorkBC.ElasticSearch.Models/Filters/JobSearchFilters.cs, src/WorkBC.ElasticSearch.Search/Queries/JobSearchQuery.cs, src/WorkBC.Shared/Extensions/JobSearchFiltersExtensions.cs, src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/filters/salary/salary.component.html
This pull request changes the default Elastic Search query so that jobs must have a salary and removes from the GUI the ability to search for jobs without a salary.  I'm taking a light touch to the changes to ensure this change passes QA as quickly as possible as I expect the client will want to push this into PROD as quickly as possible.
=> [WBCAMS-287] elastic job searches must have a salary

src/WorkBC.Tests/Fixtures/WantedXmlJobs/4049109571.xml, src/WorkBC.Tests/Fixtures/WantedXmlJobs/4049109576.xml
Modify sample job XML files used for unit testing.  Without these changes, the unit tests will complain that the job expected cannot be found.
=> [WBCAMS-287] update XML used for unit tests

src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/pagination/pagination.component.ts, src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/search-criteries/search-criteries.component.ts
My initial assumption was incorrect.  The cause of the pagination problem is that  `currentPage` is a number when navigating using paginator, but is a string when passed in from the URL.
=> [WBCAMS-278] fix job board pagination rev2

src/WorkBC.Admin/Services/SelectListService.cs
The current query LINQ query creates inefficient SQL that uses `DISTINCT` instead of  `GROUP BY`.  I've tested this locally, but only with a very small Jobs table.  Without more time, I couldn't import the text file the client provided because of the hobbled text file importer MS-SQL provides.  To test this properly, we would need:
- a copy of the database,
- permission to port forward my local machine to the AWS database,
- an import script that parses, transforms and imports the table data correctly
=> [WBCAMS-146] optimize datafirstimported query

src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/item/item.component.html
This pull request stops saved jobs from being greyed-out when expired by removing the logic that adds an "expired" css class to the job item.
=> [WBCAMS-23] do not grey-out saved jobs

src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/item/item.component.ts
Fix date comparison in the `isExpired()` method.
=> [WBCAMS-23] correct isExpired() algorithm

src/WorkBC.Web/ClientApp/projects/jb-lib/src/lib/components/item/item.component.ts
`ExpireDate`'s time component needs to be replaced with an end-of-day time in order for all jobs to expire at midnight as requested by the client.
=> [WBCAMS-23] set expiry datetime to end of day

src/WorkBC.Shared/Extensions/JobSearchFiltersExtensions.cs
Extending `BookmarkableUrl()` to include the new filters.  
Below is a screenshot of the job alert page in the current DEV environment.  Note that "Your search criteria" is blank
After implementing this PR: 
Note: the presentation between these two screenshots is slightly different because the first screenshot is taken from dev.workbc.ca (drupal) while the second screenshot is taken directly from the job board.
=> [WBCAMS-297] fix fed, prov and muni job alert filters

src/WorkBC.Data/Migrations/20231222224412_UpdateQueenCharlotteCityName.Designer.cs, src/WorkBC.Data/Migrations/20231222224412_UpdateQueenCharlotteCityName.cs, src/WorkBC.Data/README.md, src/WorkBC.ElasticSearch.Indexing/XmlParsingHelpers/XmlManualOverRides.cs
This pull request contains a migration script that:
- modifies the name of "Queen Charlotte City" to "Daajing Giids ( Queen Charlotte City )"
- rewrites the city name of newly imported Jobs to use the new name
- triggers existing jobs located in Queen Charlotte City (if any) to be renamed on the next Job update
To test, I've run the migration script locally and verified that the name is changed as expected and that any existing jobs are triggered to be updated, but since there aren't any current jobs located in Queen Charlotte City I haven't been able to verify that the update works correctly.
=> [WBCAMS-293] update queen charlotte city name

src/WorkBC.ElasticSearch.Search/Queries/JobSearchQuery.cs
Create ElasticSearch query string to search for federal government jobs using the source URL.
=> WBCAMS-377-fix-federal-jobs-filter

src/WorkBC.ElasticSearch.Search/Queries/JobSearchQuery.cs, src/WorkBC.Tests/Fixtures/WantedXmlJobs/6111648176.xml, src/WorkBC.Tests/WorkBC.Tests.csproj
To fix the federal jobs filter requires an ElasticSearch query that uses a `nested` query.  The previous pull request relied on a mappings of the `jobs_en` index that were different from what are used in DEV (and presumably TEST and PROD).
I've added an additional XML to the test suite so the federal jobs query passes.
=> [WBCAMS-377] fix federal jobs filter with nested attribute

src/WorkBC.Admin/Areas/Jobs/Controllers/JobSearchController.cs, src/WorkBC.Admin/Areas/Jobs/Services/JobService.cs, src/WorkBC.Admin/Areas/Jobs/Views/JobSearch/JobSearch.cshtml, src/WorkBC.Admin/wwwroot/js/jobs.js
Admin users have reported the following URLs do not load the page data:
https://dev-admin-jobboard.workbc.ca/jobs/JobSearch/Index
https://test-admin-jobboard.workbc.ca/jobs/JobSearch/Index 
But, the same page in PROD does load -- albeit slowly.
This PR remove queries that display total record counts at the top of the page.  If the page loads successfully after merging, we can create a new ticket to load the counts asynchronously.
=> [WBCAMS-146] reduce queries on admin controller

src/WorkBC.ElasticSearch.Indexing/Services/XmlParsingServiceWanted.cs
It appears the number format shorthand `C0` works in Windows locally, but doesn't work when the unit tests are run from Docker.
=> [WBCAMS-346] fix failing test version 2

src/WorkBC.Importers.Federal/Services/JobsTableSyncService.cs
When running the federal job importer locally, the import script crashes because of a missing null check.
=> [Unsolicited] fix federal importer crash

src/WorkBC.Importers.Federal/Services/XmlImportService.cs, src/WorkBC.Importers.Federal/WorkBC.Importers.Federal.csproj, src/WorkBC.Shared/Services/GeocodingService.cs, src/WorkBC.Tests/README.md
This pull request improves the speed of the federal job importer by ~50% when updating a job and by ~300% when importing a new job.  Key changes as follows:
- reuse the HttpClient instead of creating a new copy on every request
- call the french and english API endpoints simultaneously rather than sequentially
Some of these changes were incorporated into a previous commit (b6f06255) but then reverted (f9dc3115).
=> [WBCAMS-420] improve speed of federal jobs importer

src/WorkBC.Web/Services/SavedJobsService.cs
When the saved jobs are pulled from the database, they're currently passed to the front end without a time zone (see left screen below) whereas when the public job board pulls from ElasticSearch the data returned has a UTC timezone `+00:00` (see right screen below).
This PR sets a UTC timezone on the expiry date when returning the saved jobs so that the expiry date is treated consistently between the public facing job board and a job seekers saved jobs.  The screenshot below shows how the expiry date is received by the front end after this change is implemented.
=> [WBCAMS-310] display expiry date consistently

src/WorkBC.Importers.Wanted/Services/JobsTableSyncService.cs
When a job is deleted from by an admin, the job is re-imported when `WorkBC.Importers.Wanted` is next run.  This PR filters out deleted jobs from the wanted jobs importer so they can't be re-imported.
=> [WBCAMS-415] stop deleted jobs from being reimported

src/WorkBC.Admin/Areas/Reports/Controllers/JobSeekerAccountController.cs, src/WorkBC.Admin/Areas/Reports/Services/JobSeekerAccountReportService.cs
Remove stored procedure call.  Will run separately on a schedule instead.
set up schedule to run `usp_GenerateJobSeekerStats` on the 7th, 14th, 21st, 28th and the very last day of the month.
=> [WBCAMS-184] fix job seeker report

src/WorkBC.Admin/package-lock.json, src/WorkBC.Admin/package.json, src/WorkBC.Web/ClientApp/package-lock.json
From reading the release notes of the upgraded packages, I'm not aware of any breaking changes.
=> [WBCAMS-416] upgrade vulnerable npm packages

src/WorkBC.Web/Services/RecommendedJobsService.cs
Added a check for both null and empty Noc Codes to resolve an issue with the recommended jobs page.
=> [WBCAMS-409] fix recommended jobs page error

src/WorkBC.Data/Migrations/20240430195843_UpdateNocCodes2016Data.Designer.cs, src/WorkBC.Data/Migrations/20240430195843_UpdateNocCodes2016Data.cs, src/WorkBC.Data/Model/JobBoard/NocCode2021.cs, src/WorkBC.ElasticSearch.Indexing/Services/JobsTableSyncServiceBase.cs, src/WorkBC.ElasticSearch.Indexing/Services/XmlParsingServiceBase.cs, src/WorkBC.ElasticSearch.Indexing/Services/XmlParsingServiceWanted.cs, src/WorkBC.Importers.Wanted/Services/JobsTableSyncService.cs, src/WorkBC.Tests/Fixtures/NocFixture.cs, src/WorkBC.Tests/Fixtures/WantedXmlJobs/6178058670.xml, src/WorkBC.Tests/Fixtures/WantedXmlJobs/6178210923.xml, src/WorkBC.Tests/Tests/SearchTests.cs, src/WorkBC.Tests/WorkBC.Tests.csproj
Changes include following:
1. At this time, the TalentNeuron API only provides a NOC 2011 code in its feed. In order to ingest jobs with the new NOC 2021 system, we have to map NOC 2011 codes to NOC 2021. Have added a migration to add a new column for 2016 codes in NocCodes2021 table and populate the cells with corresponding values in relation to their 2021 code values. It looks like below after implementation. The model does not need to convert from an array to string explicitly. While reading the JSON, we store the 2016 NocCode field as a comma separated string of values and then save the same string in DB.
2. This should be done by mapping from the incoming NOC code in the Wanted / TalentNeuron feed (which is a NOC 2011/2016 code) into a NOC 2021 code, using lookup from the …
=> [NOC-333] Changes for adding Noc2021 data to Wanted importer and indexer

src/WorkBC.Indexers.Federal/appsettings.json
Some more details on the issue
The external jobs are posted for today
The last workBC job was posted July 16
The 'Date posted' filter for today shows 0 (something to do with the date stamp for external jobs maybe)?
=> WorkBC24-R3 Release V2 (TEST): Fix local configuration file
